Fix libc interposition's linking steps
As explained in <https://stackoverflow.com/a/79204761/883113>.

I'll reorder the linking order later. Right now the project doesn't even
build due to:

/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: libemilua.so.0.11.0.p/meson-generated_bc2_file_descriptor.cpp.o: in function `_GLOBAL__sub_I_bc2_file_descriptor.cpp':
/usr/include/boost/asio/detail/call_stack.hpp:119:(.text.startup+0x6e): undefined reference to `__dso_handle'
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: libemilua.so.0.11.0.p/meson-generated_bc2_file_descriptor.cpp.o: relocation R_X86_64_PC32 against undefined hidden symbol `__dso_handle' can not be used when making a shared object
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: bad value